### ISSUE TITLE
Omitir ranking

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/codecodes-api#10]
Por enquanto vamos bloquear o ranking e só mostrar no final do evento.

**Comment by Markkop** [comment]
Não é melhor fazer isso pelo front? 
Até posso botar uma flag pra desativar a resposta da API, mas como ela tá no `getStaticProps` do NextJS, ela tá protegida e só a gente tem acesso a API, então dá pra mudar direto no front.
O que acha?

https://github.com/codecon-dev/site/blob/340442c402daedb09eb7286af29bd4c653e4d0af/pages/digital/game/code-codes/index.tsx#L39

**Comment by gabrnunes** [comment]
Fechou, pode ser!
