### ISSUE TITLE
Mostrar quantos pontos a pessoa tem na hora do resgate

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/codecodes-api#11]
Acho que é legal, o que acha?

**Comment by Markkop** [comment]
É pra já ser possível.
Talvez não esteja sendo exibido no front? Vou verificar
![image](https://github.com/codecon-dev/codecodes-api/assets/16388408/5289d9e0-d424-4b7d-a3d5-977f6d80d080)

**Comment by Markkop** [comment]
Acredito que seja só dar um console.log nesse result aqui que vai estar lá em data.totalScore:
https://github.com/codecon-dev/site/blob/340442c402daedb09eb7286af29bd4c653e4d0af/components/code-codes/Claim/Claim.tsx#L37

To com um problema no Insomnia pra faciltar os testes, quando arrumar posso testar.
