### ISSUE TITLE
Cadastrar novos códigos

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/codecodes-api#9]
Precisamos fazer a lista de novos códigos para resgate

**Comment by Markkop** [comment]
ah não

**Comment by Markkop** [comment]
kk brinks, podemos usar o bot do discord de novo se pá

**Comment by Markkop** [comment]
Se me sobrar um tempo eu posso codar uma UI pra isso, acho que valeria a pena. 
Subi o bot de novo pra gente e dei uma testada, parece estar importando.
